# Generated by Django 3.0.2 on 2020-02-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_no',
            field=models.CharField(default=9860083385, max_length=100, unique=True, verbose_name='Contact Number'),
        ),
    ]
