# Generated by Django 3.0.2 on 2020-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200209_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
